# Generated by Django 4.2.3 on 2023-08-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
