# Generated by Django 4.2.3 on 2023-08-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_slug',
            field=models.SlugField(default='', max_length=40),
        ),
    ]
