# Generated by Django 4.2.3 on 2023-08-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='slug',
            new_name='post_slug',
        ),
    ]
